USE BuyPy;

CREATE ROLE IF NOT EXISTS 'WEB_CLIENT_ROLE';
CREATE ROLE IF NOT EXISTS 'BUYDB_OPERATOR_ROLE';
CREATE ROLE IF NOT EXISTS 'BUYDB_ADMIN_ROLE';

GRANT SELECT ON BuyPy.* TO 'WEB_CLIENT_ROLE';
GRANT INSERT, UPDATE ON BuyPy.Client TO 'WEB_CLIENT_ROLE';
GRANT INSERT, UPDATE ON BuyPy.`Order` TO 'WEB_CLIENT_ROLE';
GRANT INSERT, UPDATE ON BuyPy.Ordered_Item TO 'WEB_CLIENT_ROLE';
GRANT INSERT, UPDATE ON BuyPy.Recommendation TO 'WEB_CLIENT_ROLE';
GRANT DELETE ON BuyPy.`Order` TO 'WEB_CLIENT_ROLE';
GRANT DELETE ON BuyPy.Ordered_Item TO 'WEB_CLIENT_ROLE';
GRANT UPDATE (quantity) ON BuyPy.Product TO 'WEB_CLIENT_ROLE';
GRANT EXECUTE ON PROCEDURE BuyPy.CreateOrder TO 'WEB_CLIENT_ROLE';
GRANT EXECUTE ON PROCEDURE BuyPy.GetOrderTotal TO 'WEB_CLIENT_ROLE';
GRANT EXECUTE ON PROCEDURE BuyPy.AddProductToOrder TO 'WEB_CLIENT_ROLE';
GRANT EXECUTE ON PROCEDURE BuyPy.DailyOrders TO 'WEB_CLIENT_ROLE';
GRANT EXECUTE ON PROCEDURE BuyPy.AnnualOrders TO 'WEB_CLIENT_ROLE';

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON BuyPy.* TO 'BUYDB_OPERATOR_ROLE';

GRANT ALL PRIVILEGES ON BuyPy.* TO 'BUYDB_ADMIN_ROLE' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'Wilson'@'localhost' IDENTIFIED BY 'Lmxy20#a';
CREATE USER IF NOT EXISTS 'Alberto'@'localhost' IDENTIFIED BY 'Lmxy20#a';
CREATE USER IF NOT EXISTS 'Orlando'@'localhost' IDENTIFIED BY 'Lmxy20#a';

GRANT 'WEB_CLIENT_ROLE' TO 'Wilson'@'localhost';
GRANT 'BUYDB_OPERATOR_ROLE' TO 'Alberto'@'localhost';
GRANT 'BUYDB_ADMIN_ROLE' TO 'Orlando'@'localhost';

SET DEFAULT ROLE 'WEB_CLIENT_ROLE' TO 'Wilson'@'localhost';
SET DEFAULT ROLE 'BUYDB_OPERATOR_ROLE' TO 'Alberto'@'localhost';
SET DEFAULT ROLE 'BUYDB_ADMIN_ROLE' TO 'Orlando'@'localhost';

FLUSH PRIVILEGES;
